namespace HTCCSettings {
[default_interface] runtimeclass MainWindow : Microsoft.UI.Xaml.Window {
  MainWindow();

  // General settings
  Boolean IsEnabled;
  Int16 PointerSource;
  Int16 PointerSink;

  // XR_FB_hand_tracking_aim (Quest, Ultraleap Gemini 5.16+)
  Boolean PinchToClick;
  Boolean PinchToScroll;

  // PointCTRL
  Int16 PointCtrlFCUMapping;

  // Workarounds
  Boolean ForceXRExtHandTracking;
  Boolean ForceXRFBHandTrackingAim;
}

}// namespace HTCCSettings
