name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    name: Build (${{matrix.config}})
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          path: source
          fetch-depth: 0
      - name: Make build directory
        run: cmake -E make_directory build
      - name: Configure
        working-directory: build
        shell: pwsh
        run: |
          $args = @(
            "-DGITHUB_REF_TYPE=${{github.ref_type}}",
            "-DGITHUB_REF_NAME=${{github.ref_name}}"
          )
          cmake ${{github.workspace}}/source @args
      - name: Compile
        working-directory: build
        run: |
          cmake --build . `
            --config ${{matrix.config}} `
            --parallel `
            -- `
            /p:CL_MPCount=
      - name: Create installer
        working-directory: build
        run: |
          cmake --install . `
            --config ${{matrix.config}} `
            --prefix install `
            --component Default
          cd install
          iscc ..\installer.iss
    strategy:
      matrix:
        config: [RelWithDebInfo, Debug]
