name: Continuous Integration
on: [push, pull_request]
jobs:
  build:
    name: Build (${{matrix.config}})
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          path: source
          fetch-depth: 0
      - name: Make build directory
        run: cmake -E make_directory build
      - name: Configure
        working-directory: build
        shell: pwsh
        run: |
          $args = @(
            "-DGITHUB_REF_TYPE=${{github.ref_type}}",
            "-DGITHUB_REF_NAME=${{github.ref_name}}"
          )
          cmake ${{github.workspace}}/source @args
      - name: Compile
        working-directory: build
        run: |
          cmake --build . `
            --config ${{matrix.config}} `
            --parallel `
            -- `
            /p:CL_MPCount=
      - name: Install files
        working-directory: build
        run: |
          cmake --install . `
            --config ${{matrix.config}} `
            --prefix install-prefix `
            --component Default
      - name: Attach files to build
        if: ${{matrix.config != 'Debug' }}
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: build/install-prefix/**
      - name: Create installer
        working-directory: build
        run: |
          Copy-Item installer.iss install-prefix
          cd install-prefix
          iscc installer.iss
      - name: Create debug symbols zip
        working-directory: build
        run: |
          cmake --install . `
            --config ${{matrix.config}} `
            --prefix symbols `
            --component DebugSymbols
      - name: Attach installer to build
        if: ${{matrix.config != 'Debug' }}
        uses: actions/upload-artifact@v2
        with:
          name: installer
          path: build/install-prefix/HandTrackedCockpitClicking-v*.exe
      - name: Attach debug symbols to build
        if: ${{matrix.config != 'Debug' }}
        uses: actions/upload-artifact@v2
        with:
          name: symbols
          path: build/symbols/*.pdb
    strategy:
      matrix:
        config: [RelWithDebInfo, Debug]
